spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/quiz_db
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB102Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 816146297349-2709jspbk6s79q86p22odc8ple8sj41g.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:5500 # Nhớ đổi sang host mà ông chạy FrontEnd nhá
  oauth2:
    authorizedRedirectUris:
      - http://localhost:5500
